name: 'apptestai-test'
description: 'github action for apptest.ai test execution'
author: 'Jae-cheol Kim <forcemax@gmail.com>'
inputs:
  access_key:
    description: 'apptest.ai access key'
    required: true
  project_id:
    description: 'apptest.ai project id'
    required: true
  binary_path:
    description: 'package file'
    required: true
  testset_name:
    description: 'test set name (default: github commit message).'
    required: false
  time_limit:
    description: 'Test time limit (minutes) (range: 5 - 30). If the value is empty, it follows the time-limit saved in the project.'
    required: false
  use_vo:
    description: 'Whether AT&T Video Optimizer(ARO) is used. (true|false) (default: false)'
    required: false
  callback:
    description: 'Callback URL to be called after test completion.'
    required: false
  login_id:
    description: 'ID of the test account required to test the app. If the value is empty, it follows the time-limit saved in the project.'
    required: false
  login_pw:
    description: 'Password of the test account required to test the app. If the value is empty, it follows the time-limit saved in the project.'
    required: false
    
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'anchor'
  color: 'orange'
